import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { archiveAssets, archiveCategories, archiveIssuers, catalogue, categoryLabel, formatArchivedPrice, networkLabel, sourceGroups } from "@/lib/catalogue";
import { assetMediaUrl, issuerMediaUrl } from "@/lib/catalogue-media";
import styles from "./CatalogueHome.module.css";

const shelves = ["precious-metals", "treasuries", "equities", "etfs", "bonds", "private-credit", "real-estate", "art-collectibles", "commodities", "carbon"];
const compact = (value: number | null) => value === null ? "—" : "$" + new Intl.NumberFormat("en-US", {notation:"compact",maximumFractionDigits:1}).format(value);
export function CatalogueSnapshotBar() {
  return <div className={"container " + styles.snapshotBar}><span>Catalogue snapshot <time dateTime={catalogue.snapshotAt}>23 Sep 2026</time></span><Link href="/assets/?network=all"><strong>1,936</strong> assets</Link><Link href="/issuers/"><strong>50</strong> issuers</Link><Link href="/markets/"><strong>16</strong> categories &amp; networks</Link><Link href="/sources/">Data sources <ArrowUpRight size={14} /></Link></div>;
}
export function CatalogueCategoryLinks() {
  return <div className={styles.categoryLinks}>{archiveCategories.map((category) => <Link key={category.id} href={"/assets/?network=all&category=" + category.id}>{category.label}<span>{category.count.toLocaleString("en-US")}</span></Link>)}</div>;
}
export function CatalogueHome() {
  const ranking = archiveAssets.filter((asset) => asset.liquidityUsd !== null).toSorted((a,b) => (b.liquidityUsd ?? 0) - (a.liquidityUsd ?? 0)).slice(0,8);
  return <div className={"container " + styles.home}>
    <section className={styles.section}><div className={styles.heading}><div><p>Saved market depth</p><h2>Look beyond the price.</h2></div><Link className="text-link" href="/assets/?network=all">Full catalogue<ArrowRight size={16} /></Link></div><p className={styles.description}>The largest recorded liquidity figures in the archive. Each record keeps its network, source and capture date.</p><div className={styles.rankingScroll}><table><caption className={styles.srOnly}>Historical liquidity ranking</caption><thead><tr><th>Asset</th><th>Quote network</th><th>Saved liquidity</th><th>Saved price</th><th>Historical mark</th></tr></thead><tbody>{ranking.map((asset) => <tr key={asset.slug}><td><Link href={"/assets/" + asset.slug + "/"}>{assetMediaUrl(asset) ? <Image src={assetMediaUrl(asset)!} alt="" width={28} height={28} /> : null}<strong>{asset.symbol}</strong><span>{asset.issuer}</span></Link></td><td>{networkLabel(asset.chain)}</td><td>{compact(asset.liquidityUsd)}</td><td>{formatArchivedPrice(asset.priceUsd)}{asset.perOz && asset.priceUsd !== null ? " / troy oz" : ""}</td><td>{asset.stamp.state}</td></tr>)}</tbody></table></div><p className="note">Historical ranking, not a current liquidity check. OPEN / THIN / WATCH are the archive’s dated marks.</p></section>
    {shelves.map((id) => {
      const records = archiveAssets.filter((asset) => asset.category === id).toSorted((a,b) => Number(b.priceUsd !== null) - Number(a.priceUsd !== null)).slice(0,4);
      if(records.length === 0) return null;
      const count = archiveCategories.find((category) => category.id === id)?.count;
      return <section className={styles.section} key={id}><div className={styles.heading}><div><p>{count?.toLocaleString("en-US")} records in the catalogue</p><h2>{categoryLabel(id)}</h2></div><Link className="text-link" href={"/assets/?network=all&category=" + id}>View all<ArrowRight size={16} /></Link></div><div className={styles.shelf}>{records.map((asset) => <article key={asset.slug}><div className={styles.identity}>{assetMediaUrl(asset) ? <Image src={assetMediaUrl(asset)!} alt="" width={34} height={34} /> : null}<span>{networkLabel(asset.chain)}</span></div><h3>{asset.symbol}</h3><p>{asset.name}</p><small>{asset.issuer}</small><div className={styles.price}><strong>{formatArchivedPrice(asset.priceUsd)}{asset.perOz && asset.priceUsd !== null ? " / troy oz" : ""}</strong><span>{asset.priceSource ?? "No saved price"}</span></div><Link className="text-link" href={"/assets/" + asset.slug + "/"}>View record<ArrowUpRight size={14} /></Link></article>)}</div></section>;
    })}
    <section className={styles.section}><div className={styles.heading}><div><p>Behind the catalogue</p><h2>Keep the source in view.</h2></div><Link className="text-link" href="/sources/">All sources<ArrowRight size={16} /></Link></div><div className={styles.sourceGrid}>{sourceGroups.map((source) => <Link key={source.id} href={"/assets/?network=all&source=" + encodeURIComponent(source.id)}><strong>{source.count.toLocaleString("en-US")}</strong><span>{source.label}</span></Link>)}</div><div className={styles.issuers}>{archiveIssuers.slice(0,10).map((issuer) => <Link key={issuer.name} href={"/issuers/?q=" + encodeURIComponent(issuer.name)}>{issuerMediaUrl(issuer.name) ? <Image src={issuerMediaUrl(issuer.name)!} alt="" width={25} height={25} /> : null}{issuer.name}</Link>)}</div><Link className="text-link" href="/issuers/">All 50 issuers<ArrowRight size={16} /></Link></section>
    <section className={styles.section}><div className={styles.heading}><div><p>Explore &amp; plan</p><h2>More ways into the real world.</h2></div></div><div className={styles.tools}>{[{href:"/trade/",name:"Trade",description:"Connect a wallet and preview an asset buy."},{href:"/watchlist/",name:"My watchlist",description:"Keep the assets you want to follow."},{href:"/basket/",name:"Asset basket",description:"Build a basket from the complete catalogue."},{href:"/swap/",name:"Asset comparison",description:"Compare amounts using saved prices and samples."},{href:"/draw/",name:"Random discovery",description:"Find assets across categories and networks."},{href:"/account/",name:"My workspace",description:"Return to the plans saved on this device."},{href:"/docs/",name:"Documentation",description:"Understand the fields, methods and data limits."},{href:"/thesis/",name:"The GROUND thesis",description:"Give each part of your wallet a real-world purpose."}].map((tool) => <Link key={tool.href} href={tool.href}><h3>{tool.name}<ArrowUpRight size={15} /></h3><p>{tool.description}</p></Link>)}</div></section>
  </div>;
}
