import type {Metadata} from "next";
import Link from "next/link";
import { ArrowUpRight, Download } from "lucide-react";
import { catalogue } from "@/lib/catalogue";
import styles from "./Docs.module.css";
export const metadata:Metadata = {title:"Documentation",description:"Catalogue fields, sources, archive methods and working read-only data endpoints."};
const fields = [["slug / symbol / name","The preserved product identity; slugs are unique."],["issuer / backing / desc","Saved issuer and product descriptions, not a new guarantee of holder rights."],["chain / chains","chain identifies the recorded quote network; chains lists recorded deployments."],["address / pairUrl / permalink","Third-party token identity, market index and issuer product links."],["priceUsd / priceSource","A dated reference price and its provenance. Null means unavailable."],["liquidityUsd / quoteReservesUsd","Saved liquidity and the archive’s estimated quote reserves."],["marketCap / fdv / holders","Historical market and holder fields where saved; missing values stay null."],["curve / probe","Saved size/impact observations and their engine, venue, block and capture time."],["stamp","A historical classification with a reason, method and saved clean-size estimate."],["unit / unitLabel / perOz","Display-unit information. perOz prices are per troy ounce; quantity tools convert to grams using 31.1034768 grams per troy ounce. xStock display units are not raw wallet balances."]];
const endpoints = [["/api/catalogue","The complete 1,936-record archive."],["/api/assets?network=solana&limit=24","Filtered and paginated records; 1–100 per response."],["/api/assets/spyx","One asset record, or HTTP 404 when absent."],["/api/issuers","All 50 issuer records and websites."],["/api/sources","Price provenance groups and archive counts."]];
export default function DocsPage() {return <div className={"container " + styles.page}><div className="page-intro"><p>Documentation</p><h1>Read the data.<br/>Understand the method.</h1><p>Working catalogue endpoints, preserved fields and the boundaries of this research workspace.</p></div><nav className={styles.contents} aria-label="Documentation sections">{["overview","sources","fields","marks","api","market","wallet","tools"].map((id) => <a key={id} href={"#" + id}>{id === "api" ? "Data API" : id[0].toUpperCase() + id.slice(1)}</a>)}</nav>
    <section id="overview"><h2>The complete archive.</h2><p>GROUND preserves 1,936 assets, 50 issuers, 16 categories and 16 networks from the saved catalogue dated 23 Sep 2026. You can search every record, browse issuer websites and inspect its source data.</p><a className="button secondary" href="/api/catalogue?download=1"><Download size={16}/>Download complete JSON</a><p className="note">The imported archive is byte-for-byte identical to the supplied catalogue. The original project’s token promotion is separate and is not included.</p></section>
    <section id="sources"><h2>More than one kind of price.</h2><div className={styles.four}><div><h3>DEX pair</h3><p>55 saved market-pair price observations. Recorded venue and quote currency are preserved.</p></div><div><h3>Jupiter price</h3><p>145 price references from the Solana discovery source; 80 assets also have historical probe curves.</p></div><div><h3>Issuer price / NAV</h3><p>805 issuer product prices and 3 NAV references. They are distinct from executable secondary-market quotes.</p></div><div><h3>No saved price</h3><p>928 records retain their identity and sources without a saved price. They display —.</p></div></div><Link className="text-link" href="/sources/">Explore all source groups<ArrowUpRight size={15}/></Link></section>
    <section id="fields"><h2>The record fields.</h2><div className={styles.tableScroll}><table><thead><tr><th>Fields</th><th>Meaning</th></tr></thead><tbody>{fields.map(([name,meaning]) => <tr key={name}><th scope="row"><code>{name}</code></th><td>{meaning}</td></tr>)}</tbody></table></div></section>
    <section id="marks"><h2>OPEN / THIN / WATCH.</h2><p>These are the archive’s historical marks. Its price-impact cap was {catalogue.rule.impactCap * 100}%, with a saved OPEN threshold of ${catalogue.rule.openMinUsd.toLocaleString("en-US")}. Read each record’s reason and method: 80 assets include measured or partial probe observations; other classifications may use estimates.</p><div className={styles.four}><div><h3>OPEN · 59</h3><p>The archive classified the record as meeting its clean-size rule at capture.</p></div><div><h3>THIN · 88</h3><p>The archive recorded more limited capacity under its rule.</p></div><div><h3>WATCH · 1,789</h3><p>The archive did not establish a sufficiently usable route or data coverage.</p></div><div><h3>Read the sample</h3><p>A mark describes a saved observation. It is not a present-day availability check.</p></div></div><p>The archived quote-reserve estimate uses liquidity divided by two. Impact values are ratios: 0.02 is 2%. Connecting lines on a chart are visual guides and do not generate new quotes.</p></section>
    <section id="api"><h2>Read-only data endpoints.</h2><p>These endpoints serve the actual saved data in this application. They do not contact providers for live prices.</p><div className={styles.endpoints}>{endpoints.map(([url,description]) => <a href={url} target="_blank" rel="noopener noreferrer" key={url}><code>GET {url}</code><span>{description}</span><ArrowUpRight size={15}/></a>)}</div><p className="note">Assets filters: q, category, network, issuer, source, limit and offset. The network filter uses the primary quote network. Invalid pagination returns HTTP 400. Filtered API responses include snapshotAt and mode: archive. The complete JSON endpoint preserves the original archive structure without adding fields.</p></section>
    <section id="market"><h2>Fetched market references.</h2><p><code>GET /api/quotes?slugs=spyx,nvdax</code> fetches indexed DEX Screener pairs for up to 24 catalogue slugs. Only saved addresses are queried. The base-token address and quote network must match the record. The highest-liquidity priced pair supplies the reference.</p><p>The response includes provider, mode: market-reference, requestedAt, fetchedAt and quotes. Each quote has an available, unavailable, unsupported or error status, with priceUsd, liquidityUsd, volume24h, change24h, venue and source link where available. providerQuoteAt remains null: a fetch timestamp is not the provider’s price timestamp.</p><p>Requests time out and surface errors. A 30-second server cache avoids duplicate loads; market references older than two minutes are labelled stale. These references do not provide an execution quote or minimum received amount.</p><a className="text-link" href="https://docs.dexscreener.com/api/reference" target="_blank" rel="noopener noreferrer">DEX Screener API documentation<ArrowUpRight size={15}/></a></section>
    <section id="wallet"><h2>Wallet connection and Trade.</h2><p>GROUND connects supported Solana wallets through Wallet Standard. Connection reads the public account and can request its mainnet SOL balance. Account changes and disconnection update the interface. No message or transaction is signed.</p><p>Trade offers asset selection, a sample USDC/USD amount, a slippage preference and market-price quantity estimates. Trading and network fees stay unquoted. The buy action is disabled until an execution service is integrated; it never reports a completed buy.</p><Link className="text-link" href="/trade/">Open Trade<ArrowUpRight size={15}/></Link></section>
    <section id="tools"><h2>The research tools.</h2><div className={styles.four}><div><h3>Blueprint</h3><p>Explore a category allocation using your sample budget.</p><Link href="/blueprint/" className="text-link">Build a blueprint</Link></div><div><h3>Basket</h3><p>Select products across the complete catalogue, set weights and save a device-local plan.</p><Link href="/basket/" className="text-link">Build a basket</Link></div><div><h3>Compare</h3><p>Compare quantities using saved prices or exact archived samples. Missing data remains unavailable.</p><Link href="/swap/" className="text-link">Compare assets</Link></div><div><h3>Discover</h3><p>Randomly explore assets in a category or network. Nothing is minted or awarded.</p><Link href="/draw/" className="text-link">Explore randomly</Link></div></div><p>Watchlists and plans are saved in your browser. Filter links can be shared; plans can be exported, copied and imported with validation. Wallet connection is separate from planning records. No transaction is executed, and a GROUND community token does not grant rights to these third-party assets.</p></section>
  </div>;}
